# services:
#   nginx:
#     image: nginx:latest
#     container_name: nginx_proxy
#     volumes:
#       - /home/kcmorris/GenAIxRad-Viewer/platform/app/.recipes/Nginx-Orthanc/config/nginx.conf:/etc/nginx/nginx.conf # Correct path for nginx.conf
#       - /home/kcmorris/GenAIxRad-Viewer/platform/app/.recipes/Nginx-Orthanc/ssl:/etc/nginx/ssl # SSL certificates
#     ports:
#       - '80:80'
#       - '443:443'
#     depends_on:
#       - orthanc
#     restart: always

#   orthanc:
#     image: jodogne/orthanc-plugins
#     container_name: orthancPACS
#     volumes:
#       - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro # Orthanc config inside Docker
#       - ./volumes/orthanc-db/:/var/lib/orthanc/db/ # Data persistence
#     restart: unless-stopped
#     ports:
#       - '4242:4242' # Orthanc REST API
#       - '8042:8042' # Orthanc HTTP

# Reference:
# - https://docs.docker.com/compose/compose-file
# - https://eclipsesource.com/blogs/2018/01/11/authenticating-reverse-proxy-with-keycloak/

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - /home/kcmorris/GenAIxRad-Viewer/platform/app/.recipes/Nginx-Orthanc/config/nginx.conf:/etc/nginx/nginx.conf  # Correct path for nginx.conf
      - /home/kcmorris/GenAIxRad-Viewer/platform/app/.recipes/Nginx-Orthanc/ssl:/etc/nginx/ssl  # SSL certificates
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - orthanc
    restart: always

  orthanc:
    image: jodogne/orthanc-plugins
    container_name: orthancPACS
    volumes:
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro  # Orthanc config inside Docker
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/  # Data persistence
    restart: unless-stopped
    ports:
      - '4242:4242'  # Orthanc REST API
      - '8042:8042'  # Orthanc HTTP